const type = {
	ADD_MALL_CART: 'ADD_MALL_CART', //商城-添加商品进购物车
	REDUCE_MALL_CART: 'REDUCE_MALL_CART', //商城-减少商品进购物车
	CLEAR_MALL_CART: 'CLEAR_MALL_CART', //商城-清空购物车
	GET_MALL_CART: 'GET_MALL_CART', //商城-获取购物车列表
	SELECTALL_MALL_CART: 'SELECTALL_MALL_CART', //商城-全选购物车列表
	SELECT_MALL_CART: 'SELECT_MALL_CART', //商城-勾选购物车
	CANCEL_ACTIVE: 'CANCEL_ACTIVE', //商城-购物车选中状态取消
}
